# SPDX-FileCopyrightText: 2025 Tobias Böhm <code@aibor.de>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version: "2"

linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - funlen
    - noinlineerr
    - paralleltest
    - varnamelen
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    ireturn:
      allow:
        - error
        - stdlib
        - link.Link
    lll:
      line-length: 80
    mnd:
      ignored-functions:
        - ^cobra\..*NArgs$
    nlreturn:
      block-size: 2
    revive:
      rules:
        - name: package-comments
          disabled: true
    staticcheck:
      checks:
        - all
        - -ST1000
  exclusions:
    generated: strict
    rules:
      - linters:
          - gochecknoglobals
          - ireturn
        path: (.+)_test\.go

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      max-len: 80
