# SPDX-FileCopyrightText: 2024 Tobias Böhm <code@aibor.de>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - funlen
    - err113
    - paralleltest
    - varnamelen
    - wrapcheck

linters-settings:
  errorlint:
    errorf: false

  exhaustive:
    default-signifies-exhaustive: true

  gosec:
    excludes:
      - G204

  mnd:
    ignored-functions:
      - '^cobra\..*NArgs$'

  revive:
    rules:
      - name: package-comments
        disabled: true

  stylecheck:
    checks: 
      - "all"
      - "-ST1000"

issues:
  exclude-use-default: false
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - gochecknoglobals
        - ireturn
