# SPDX-FileCopyrightText: 2024 Tobias Böhm <code@aibor.de>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - exportloopref
    - funlen
    - paralleltest
    - varnamelen

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

  lll:
    line-length: 80

  mnd:
    ignored-functions:
      - '^cobra\..*NArgs$'

  nlreturn:
    block-size: 2

  revive:
    rules:
      - name: package-comments
        disabled: true

  stylecheck:
    checks: 
      - "all"
      - "-ST1000"

issues:
  exclude-use-default: false
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - gochecknoglobals
        - ireturn
