// Code generated by "stringer -type Exceed2GoCounterKey -trimprefix Exceed2GoCounterKey -output exceed2go_counter_key_string.go exceed2go_bpfel.go"; DO NOT EDIT.

package bpf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Exceed2GoCounterKeyIPV6PACKET-0]
	_ = x[Exceed2GoCounterKeyTO_TARGET-1]
	_ = x[Exceed2GoCounterKeyHOP_FOUND-2]
	_ = x[Exceed2GoCounterKeyICMP_PACKET-3]
	_ = x[Exceed2GoCounterKeyICMP_ECHO_REQUEST-4]
	_ = x[Exceed2GoCounterKeyICMP_CORRECT_CHECKSUM-5]
	_ = x[Exceed2GoCounterKeyCOUNTER_MAX_ENTRIES-6]
}

const _Exceed2GoCounterKey_name = "IPV6PACKETTO_TARGETHOP_FOUNDICMP_PACKETICMP_ECHO_REQUESTICMP_CORRECT_CHECKSUMCOUNTER_MAX_ENTRIES"

var _Exceed2GoCounterKey_index = [...]uint8{0, 10, 19, 28, 39, 56, 77, 96}

func (i Exceed2GoCounterKey) String() string {
	if i >= Exceed2GoCounterKey(len(_Exceed2GoCounterKey_index)-1) {
		return "Exceed2GoCounterKey(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Exceed2GoCounterKey_name[_Exceed2GoCounterKey_index[i]:_Exceed2GoCounterKey_index[i+1]]
}
