# SPDX-FileCopyrightText: 2024 Tobias Böhm <code@aibor.de>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Generate

on:
  workflow_call:
    inputs:
      llvm-version:
        default: "19"
        type: string
      artifact-name:
        required: true
        type: string

permissions:
  contents: read

jobs:
  bpf:
    name: BPF
    runs-on: ubuntu-24.04
    steps:
      - name: Install packages
        run: sudo apt-get install -y --no-install-recommends llvm clang
        env:
          DPKG_FRONTEND: noninteractive

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Generate
        run: |
          env PATH="$PATH:/usr/lib/llvm${{ inputs.llvm-version }}/bin" make -B bpf

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ inputs.artifact-name }}"
          path: |
            internal/bpf/*_bpfel.*
            internal/bpf/*_string.go
