name: Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  clangFormat:
    name: Clang Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: bpf
          exclude: libbpf
          extensions: c
          clangFormatVersion: 14

  go:
    name: GolangCI Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - uses: actions/checkout@v3
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: latest
      - name: Run tests
        run: go test -v -race ./...
