name: Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  clangFormat:
    name: Clang Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: bpf
          exclude: libbpf
          extensions: c
          clangFormatVersion: 14

  go:
    name: Go Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - uses: actions/checkout@v3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Run go test
        run: sudo $(which go) test -v -cover -coverprofile cover.out ./...

      - name: Run go tool cover
        run: go tool cover -func=cover.out
